//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.WCFServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mSucursal", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio.Entidad")]
    [System.SerializableAttribute()]
    public partial class mSucursal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_registro {
            get {
                return this.Fecha_registroField;
            }
            set {
                if ((this.Fecha_registroField.Equals(value) != true)) {
                    this.Fecha_registroField = value;
                    this.RaisePropertyChanged("Fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreBanco {
            get {
                return this.NombreBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreBancoField, value) != true)) {
                    this.NombreBancoField = value;
                    this.RaisePropertyChanged("NombreBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSucursal {
            get {
                return this.NombreSucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSucursalField, value) != true)) {
                    this.NombreSucursalField = value;
                    this.RaisePropertyChanged("NombreSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBanco {
            get {
                return this.idBancoField;
            }
            set {
                if ((this.idBancoField.Equals(value) != true)) {
                    this.idBancoField = value;
                    this.RaisePropertyChanged("idBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerSucursalesBanco", ReplyAction="http://tempuri.org/IService1/ObtenerSucursalesBancoResponse")]
        AplicacionWeb.WCFServicio.mSucursal[] ObtenerSucursalesBanco(int idBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerSucursalesBanco", ReplyAction="http://tempuri.org/IService1/ObtenerSucursalesBancoResponse")]
        System.Threading.Tasks.Task<AplicacionWeb.WCFServicio.mSucursal[]> ObtenerSucursalesBancoAsync(int idBanco);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AplicacionWeb.WCFServicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AplicacionWeb.WCFServicio.IService1>, AplicacionWeb.WCFServicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionWeb.WCFServicio.mSucursal[] ObtenerSucursalesBanco(int idBanco) {
            return base.Channel.ObtenerSucursalesBanco(idBanco);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.WCFServicio.mSucursal[]> ObtenerSucursalesBancoAsync(int idBanco) {
            return base.Channel.ObtenerSucursalesBancoAsync(idBanco);
        }
    }
}
